version: "2.1"
services:
  libreoffice:
    image: ghcr.io/linuxserver/libreoffice
    container_name: libreoffice
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /path/to/config:/config
    ports:
      - 3000:3000
    restart: unless-stopped