version: '3'  
services:
  maven:
    build: .
    container_name: maven
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: "no"
    privileged: true
    volumes:
      - ./app:/usr/src/mymaven
      - /etc/localtime:/etc/localtime
    command: [
      'mvn',
      'clean',
      'package'
    ]