version: '3'

services: 
  flowerrss:
    image: indes/flowerss-bot
    volumes: 
      - ./data:/root/.flowerss
    restart: always
    environment: 
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    networks: 
      - default