version: '3.3'
services:
  komga:
    image: gotson/komga
    container_name: komga
    volumes:
      - type: bind
        source: ./app/config
        target: /config
      - type: bind
        source: ./app/data
        target: /data
      - type: bind
        source: /etc/timezone
        target: /etc/timezone
        read_only: true
    ports:
      - 8080:8080
    user: "1000:1000"
    environment:
      - <ENV_VAR>=<extra configuration>
    restart: unless-stopped