version: "3.2"
services:
  nginxWebUi-server:
    image: cym1102/nginxwebui:2.5.8
    volumes:
      - ./nginxWebUI:/home/nginxWebUI
    environment:
      BOOT_OPTIONS: "--server.port=8080"
    privileged: true
    network_mode: "host"