version: "3"

services:
  gotify:
    image: gotify/server
    ports:
      - 8080:80
    environment:
      - "TZ=Asia/Shanghai"
      - GOTIFY_DEFAULTUSER_PASS=custom
    volumes:
      - "./gotify_data:/app/data"