version: "3.5"
services:
  homeassistant:
    image: linuxserver/homeassistant
    container_name: homeassistant
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./data/config:/config
    # devices:
    #   - /path/to/device:/path/to/device
    restart: unless-stopped