version: '3'


networks:
    app001:
      external: false

services:
  moodle:
    image: moodlehq/moodle-php-apache:7.3
    container_name: moodle
    environment:
        - USER_UID=1000
        - USER_GID=1000
    restart: always
    privileged: true
    networks:
        - app001
    volumes:
      - ./moodle:/var/www/html
      - ./phpunitdata:/var/www/phpunitdata
      - ./behatdata:/var/www/behatdata
      - ./behatfaildumps:/var/www/behatfaildumps
      - ./moodledata:/var/www/moodledata
      - /etc/localtime:/etc/localtime
    ports:
      - "9380:80"
    depends_on:
      - db

  db:
    image: mariadb
    volumes:
      - database:/var/lib/mysql:rw
    restart: always
    networks:
      - app001
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: moodle
      MYSQL_USER: moodle
      MYSQL_PASSWORD: 123456
volumes:
  database: