version: '3'

services:
  server:
    image: plone:alpine
    container_name: plone
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    volumes:
      - ./data/blobstorage:/data/blobstorage
      - ./data/filestorage:/data/filestorage 
      - /etc/localtime:/etc/localtime
    ports:
      - "8080:8080"