version: "2.1"
services:
  papermerge:
    image: linuxserver/papermerge
    container_name: papermerge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - REDIS_URL= #optional
    volumes:
      - ./papermerge/config:/config
      - ./papermerge/data:/data
    ports:
      - 9308:8000
    restart: unless-stopped