version: '3.1'

networks:
  phpmyadmin:
    external: false

services:
  db:
    image: mariadb:10.3
    restart: always
    container_name: db
    networks:
      - phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: notSecureChangeMe

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    networks:
      - phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1