version: "2.1"
services:
  dillinger:
    image: linuxserver/dillinger
    container_name: dillinger
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./data/config:/config
    ports:
      - 8080:8080
    restart: unless-stopped