version: "2.1"
services:
  pixapop:
    image: ghcr.io/linuxserver/pixapop
    container_name: pixapop
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - APP_USERNAME=admin #optional
      - APP_PASSWORD=admin #optional
    volumes:
      - /path/to/config:/config
      - /path/to/photos:/photos
    ports:
      - 80:80
    restart: unless-stopped