version: '3'

services:
  mango:
    image: hkalexling/mango
    container_name: mango
    expose:
      - 9000
    ports:
      - 9000:9000
    volumes:
      - ~/mango:/root/mango
      - ~/.config/mango:/root/.config/mango