version: "2.1"
services:
  pydio-cells:
    image: ghcr.io/linuxserver/pydio-cells
    container_name: pydio-cells
    hostname: pydio-cells
    environment:
        - PUID=1000
        - PGID=1000
        - TZ=Europe/London
        - EXTERNALURL=sever.develop.ufs.pub
        - SERVER_IP=129.211.208.41 #optional
    volumes:
        - ./config:/config
    ports:
        - 8080:8080
        - 33060:33060 #optional
    restart: unless-stopped
    depends_on:
        - db

  db:
        image: mysql:5.7
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
          MYSQL_ROOT_PASSWORD: 123456
          MYSQL_DATABASE: cell
          MYSQL_USER: user
          MYSQL_PASSWORD: 123456
        volumes:
          - "./docker_volumes/mysql:/var/lib/mysql"