version: '3'

networks:
  sqlserver:
    external: false
services:
  sqlserver:
     image: mcr.microsoft.com/mssql/server:2017-latest
     container_name: sqlserver
     restart: always
     privileged: true
     networks:
      - sqlserver
     ports:
      - 1433:1433
     environment:
      - "ACCEPT_EULA=Y"
      - "SA_PASSWORD=12345678"


