# by default, the Ghost image will use SQLite (and thus requires no separate database container)
# we have used MySQL here merely for demonstration purposes (especially environment-variable-based configuration)

version: '3.1'

networks:
  ghost:
    external: false
    

services:

  ghost:
    image: ghost:3-alpine
    container_name: ghost
    restart: always
    ports:
      - 9510:2368
    networks:
      - ghost
    environment:
      # see https://ghost.org/docs/config/#configuration-options
      database__client: mysql
      database__connection__host: ghostdb
      database__connection__user: root
      database__connection__password: example
      database__connection__database: ghost
      # this url value is just an example, and is likely wrong for your environment!
      url: http://localhost:9510
      # contrary to the default mentioned in the linked documentation, this image defaults to NODE_ENV=production (so development mode needs to be explicitly specified if desired)
      #NODE_ENV: development
    depends_on:
      - ghostdb

  ghostdb:
    image: mysql:5.7.34
    restart: always
    container_name: ghostdb
    networks:
      - ghost
    ports:
      - 3306:3306
    privileged: true
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: ghost