version: "2.1"
services:
  pwndrop:
    image: ghcr.io/linuxserver/pwndrop
    container_name: pwndrop
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - SECRET_PATH=/pwndrop #optional
    volumes:
      - /path/to/appdata:/config
    ports:
      - 8080:8080
    restart: unless-stopped