version: '3'

services:
  server:
    image: jlesage/nginx-proxy-manager
    container_name: nginx-pm
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    privileged: true
    volumes:
      - /docker/appdata/nginx-proxy-manager:/config:rw
      - /etc/localtime:/etc/localtime
    ports:
      - "8181:8181"
      - "8080:8080"
      - "9443:443"
      - "9080:80"